name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Rustfmt Check
        run: cargo fmt -- --check
      - name: Clippy Check
        run: cargo clippy --all-targets --all-features -- -D warnings
